### ISSUE TITLE
Syncing takes a long time

### ISSUE THREAD

**Issue by NorfairKing** [ellie/atuin#163]
I just started an `atuin sync` after the first `atuin import auto` and it's been running for minutes, to sync about 10K entries.
I'd expect this to take <1 second.

I apologise for the load of issues all at once, I'm just excited (and I'd be happy to help!) :D

EDIT: Every sync request actually takes minutes, not just the first one.
I recommend you use something like a rust equivalent of  [`appendful`](https://github.com/NorfairKing/appendful), because if I understand [this source](https://github.com/ellie/atuin/blob/0b9dc6696beeb0c0460775d304dc24491b7a0d66/atuin-server/src/handlers/history.rs#L19-L54) (and I definitely don't claim to), the entire history is sent over on every sync.

**Comment by ellie** [comment]
We aren't syncing the whole history every time, we essentially maintain two cursors into history. One for the last item we have, and another for when we last synced. History is listed based on that!

It does occasionally have issues though, and I haven't been able to narrow down why. I've been meaning to replace the current sync with something more calendar-based, which would be much more reliable! Just need to get the time 😅

It's probably doing this because there's more on the remote than you have locally, so it's trying to resolve it. Maybe try passing the --full flag to a sync and see if that resolves it?

**Comment by ellie** [comment]
This has taken much longer to sort than I expected, but it should now be resolved as of the latest `main`. I've deployed this to the public server too, so you should notice improvement there! I'll be continuing to work on this to ensure syncing is rapid :D
