### ISSUE TITLE
`atuin import` should support bash `HISTTIMEFORMAT="%F %T "`

### ISSUE THREAD

**Issue by vincentdephily** [ellie/atuin#167]
# Setup

This is a common bash config to enable storing timestamps, and is recommended by tools like[ hstr](https://github.com/dvorka/hstr). It result in a history file looking like
```
#1627034544
ls
#1627034556
echo <<EOF
multi
line
EOF
```

# Observed
When running `atuin import bash`, all the timestamps end up imported as actual commands.

# Expected
`atuin import` should at least not confuse timestamps as commands, and ideally parse those timestamps as useful metadata.

**Comment by cyqsimon** [comment]
> This is fixed by #747

It *almost* fixes it.

The example provided by OP was something I have not considered. Turns out `.bash_history` ***can*** include multi-line history entries when used with here document syntax. Oh Bash, why must you be like this?

It turns out Bash's built-in <kbd>Ctrl</kbd> + <kbd>r</kbd> search has trouble interpreting this as well which is funny.  So technically my import implementation is "just as broken" as Bash's implementation 😅. (Which I guess makes it okay?)

One last bit of stupidity is that the line feed character at the end of `EOF` will get recorded in `.bash_history` too (*why Bash, WHY?*), so it will create an empty line. I probably should filter that. I'll make a small PR for this.
