### ISSUE TITLE
Add stats summary

### ISSUE THREAD

**Issue by ellie** [ellie/atuin#18]
Instead of `atuin stats all`, it should have the same functionality but just for `atuin stats`. A little neater and more intuitive that way.

`atuin stats day 01/01/2021` could then become `atuin stats 01/01/2021`

**Comment by satyarths** [comment]
Hi there 👋🏽 ,

I was playing around with atuin (and rust) and was looking into something that I could pick up. Wanted to check in if thsi issue is still valid.  And if so can you help in fleshing this out a bit more?

From what  I understand;

The `atuin stats`  could be:

```shell
> atuin stats last friday 
# displays  statistics for last friday

> atuin stats 01/01/2022
# displays  statistics for 1st Jan '22

> atuin stats monday
# displays  statistics for last monday

> atuin stats march
# displays stats for last march (2022-03-01 to 2022-03-31) , this currently displays for 1st March '22 only.
```

**Comment by conradludgate** [comment]
Yeah that looks correct. The stats logic is already present in the Day subcommand, it just needs to be reshuffled a bit

**Comment by satyarths** [comment]
In order to consider reducing parsing complexity ,  I would also propose  simplying how it is currently parsed. 
i.e. `atuin stats friday` can be considered equivalent to `atuin stats last friday`. Any day  of the week would correspond to the the nearest past date and if it needs to be more specific , the user could specify an explicity date. 
wdyt about this?
