### ISSUE TITLE
`atuin search -i` can't enter result into terminal

### ISSUE THREAD

**Issue by OnePieceJoker** [ellie/atuin#363]
As the title says, when I press enter in the search ui, I can't paste the content to the terminal

atuin 0.9.1
GNU bash, version 5.1.16

https://user-images.githubusercontent.com/25676220/165783956-d565cd28-88c6-4535-9cb5-780c447d0e69.mp4

**Comment by ellie** [comment]
The search TUI isn't really intended to be called manually. Because of how the rendering works, the command you select isn't written to stdout as you might expect

If you want to call it yourself, you might find this useful: https://github.com/ellie/atuin/blob/7cdd00b56fbc937316e6669960792d807ad7e308/src/shell/atuin.zsh#L37

**Comment by OnePieceJoker** [comment]
> The search TUI isn't really intended to be called manually. Because of how the rendering works, the command you select isn't written to stdout as you might expect
> 
> If you want to call it yourself, you might find this useful:
> 
> https://github.com/ellie/atuin/blob/7cdd00b56fbc937316e6669960792d807ad7e308/src/shell/atuin.zsh#L37

Thanks, I know why
