### ISSUE TITLE
Asking for support to Nushell

### ISSUE THREAD

**Issue by flyingfish120** [ellie/atuin#388]
Nushell is an another shell made in rust
[https://github.com/nushell/nushell](url)

**Comment by conradludgate** [comment]
We would love to support nushell but sadly they don't expose the functionality we need.

See: https://github.com/ellie/atuin/pull/182#issuecomment-1115758238

**Comment by azzamsa** [comment]
@fish4terrisa-MSDSM Nushell had a feature to record history into sqlite database containing timestamp, duration, working directory, exit code, etc. https://github.com/nushell/nushell/commit/42dbfd1fa0866c143aeb38a12e88091b4e611e7f. You can easily sync the sqlite db between your machines using your preferred tools.

**Comment by pprkut** [comment]
With https://github.com/nushell/nushell/issues/3872 closed, does this need to be revisited? Or is support for nushell now already covered?

**Comment by conradludgate** [comment]
It indeed looks like we can implement support now!

**Comment by patricksjackson** [comment]
The only difficulty with nushell is that atuin expects to get the command itself in the preexec hook, which nushell doesn't yet support, see #487 and https://github.com/nushell/nushell/issues/6264

So it is possible to write an integration for nushell, but we need to let atuin take the cmd text in `atuin history end` instead of `atuin history start`

**Comment by conradludgate** [comment]
According to the docs, there is the `pre_execution` hook
