### ISSUE TITLE
"UP" key doesn't show UI on bash

### ISSUE THREAD

**Issue by Merrick28** [ellie/atuin#498]
Hello,

I have the (wonderful) UI chen I use ctrl+R, but not when I use the up key. According to the readme : "rebind up and ctrl-r with a full screen history search UI"

How can I make sure the "up" key has the same UI that ctrl+r ?

Thanks in advance

**Comment by dotsam** [comment]
This was fixed by #445 but that hasn't made it into a release yet. The PR also fixed an issue where typed text wasn't populated when pressing up. Until a new release is cut, you could download https://github.com/ellie/atuin/blob/main/src/shell/atuin.bash and instead of running `eval "$(atuin init bash)"` in your shell profile, you could source that init script directly.

**Comment by Merrick28** [comment]
Perfect, thanks a lot !
