### ISSUE TITLE
`Ctrl+C` as well as `Esc` to exit

### ISSUE THREAD

**Issue by bl-ue** [ellie/atuin#52]
I'm used to hitting <kbd>Ctrl+C</kbd> to exit, and it can be vexing to have to use <kbd>Esc</kbd> instead.  Is this configurable?

**Comment by ellie** [comment]
I've just opened a PR that should sort this out! Once it's merged you should be able to run `main` from source (if you're ok with that), otherwise I'll test it properly + cut a patch release tomorrow (it's getting late here)

>  Is this configurable?

This is a question I'd love to reply with "yes" to though. It would be great to have more configurable key bindings, as then Atuin could more easily fit what people want.

**Comment by bl-ue** [comment]
Thank you! That was really fast! ⏩
