### ISSUE TITLE
Importing fish history fails if HISTFILE is set

### ISSUE THREAD

**Issue by patricksjackson** [ellie/atuin#572]
In my config I primarily use `fish`, however I have set the `HISTFILE` variable in my bash login shell to force the location of the bash history file, and that variable gets picked up by the fish shell. `fish` ignores the `HISTFILE` variable to avoid conflicts and confusion with bash/zsh. See: https://fishshell.com/docs/current/cmds/history.html

Atuin defaults to using the `HISTFILE` variable if it is set, which breaks importing the fish history. I was able to force it by clearing that variable and running the import again.

The problem is in the function `get_histpath`. It's possible the ordering of the if statement can just be switched, but I haven't checked what impact that will have on other shells.

https://github.com/ellie/atuin/blob/5e2c438dabc74d7e87fad46c725501753a0a8a26/atuin-client/src/import/mod.rs#L64-L73

**Comment by ellie** [comment]
Oh interesting! Thanks for reporting this.

We probably just want to adjust the fish importer so that instead of calling `get_histpath`

https://github.com/ellie/atuin/blob/5e2c438dabc74d7e87fad46c725501753a0a8a26/atuin-client/src/import/fish.rs#L49

we instead just use the default, as per this function

https://github.com/ellie/atuin/blob/5e2c438dabc74d7e87fad46c725501753a0a8a26/atuin-client/src/import/fish.rs#L20-L41

I'll follow up with something later, unless you fancy making a PR? 🙏
