### ISSUE TITLE
Fedora Linux installation fails when `redhat-lsb-core` package is not installed

### ISSUE THREAD

**Issue by smidm** [ellie/atuin#590]
Installation on Fedora 36 fails unless is the `redhat-lsb-core` package installed.

Without `redhat-lsb-core`:
```
Detected Linux!
Checking distro...
lsb_release could not be found, unable to determine your distribution
If you are using Arch Linux, please get community/lsb-release
```

The installation succeeds with `redhat-lsb-core` and `crate` packages installed.

**Comment by patricksjackson** [comment]
It just fell back to using `cargo` to install atuin right? I think it would fall into [this function](https://github.com/ellie/atuin/blob/main/install.sh#L155), since there's no Fedora package.

If that's the case, the best solution is to probably just rewrite [that section of the install script](https://github.com/ellie/atuin/blob/main/install.sh#L91) to fall back to installing from cargo after asking for user confirmation, rather than forcing the user to install that other package.

**Comment by uber6** [comment]
It does not fallback to cargo. It just quits.
