### ISSUE TITLE
[Feature Request] Custom keyboard shortcuts

### ISSUE THREAD

**Issue by stevenxxiu** [ellie/atuin#610]
Thanks for the great project!

It would be great for there to be custom keyboard shortcuts for each action. e.g. I often use `Ctrl + LeftArrow`, `Ctrl + RightArrow`, `Home`, `End`, `Delete`, which don't work in the editor. I'm sure other people might also have their own preferences.

This can be done by allowing configurable escape sequences, or one of the libraries in [Comprehensive keyboard handling in terminals - kitty](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). I know that [Broot](https://github.com/Canop/broot)  uses [Crossterm](https://github.com/crossterm-rs/crossterm/).

**Comment by patricksjackson** [comment]
To clarify, I'm assuming you mean custom keyboard shortcuts inside the interactive search ui, `atuin search --interactive`?

If there are shortcuts you think make sense to add universally, it should be fairly simple to add them. The inputs are handled [with this match statement](https://github.com/ellie/atuin/blob/2b7ecabec22e2c127a09498efb894a1ae2b70923/src/command/client/search/interactive.rs#L71).

However adding the ability to have _user-defined_ keyboard shortcuts would be a decent chunk of work, since you'd need to define some sort of API for the UI and commit to supporting it. Personally I don't think it's worth the effort.

**Comment by stevenxxiu** [comment]
> To clarify, I'm assuming you mean custom keyboard shortcuts inside the interactive search ui, `atuin search --interactive`?

Yup that's what I mean

> However adding the ability to have _user-defined_ keyboard shortcuts would be a decent chunk of work, since you'd need to define some sort of API for the UI and commit to supporting it. Personally I don't think it's worth the effort.

I'm not too sure on what you mean here on API for the UI, but fair enough. The keyboard shortcuts I use are the pretty usual ones, so I think adding them universally makes sense.

The ones I want are pretty self-explanatory:

- `Ctrl + LeftArrow`: Previous word.
- `Ctrl + RightArrow`: Next word.
- `Home`: Go to start of line.
- `End`: Go to end of line.
- `Delete`: Delete next character.
- `Ctrl + Backspace`: Delete previous word.
- `Ctrl + Delete`: Delete next word.

The library that's being used, [Termion](https://docs.rs/termion/latest/termion/), supports the `Ctrl` combinations here. In particular, [ctrl + arrow? (#194) · Issues · redox-os / termion · GitLab](https://gitlab.redox-os.org/redox-os/termion/-/issues/194) was created a year ago with no response.

Would moving to  [Crossterm](https://github.com/crossterm-rs/crossterm/) make sense?

**Comment by conradludgate** [comment]
Those keybindings would make sense to be universal!

Crossterm is a WIP (#331) but it's currently blocked due to a bug on zsh/macos (which is my work setup so I'm definitely not going to let that bug through 😂)
