### ISSUE TITLE
Feature: Support syncing with S3 bucket

### ISSUE THREAD

**Issue by jpds** [ellie/atuin#684]
I'd like to synchronize atuin with an S3 bucket (rather than use a server). The crate to use for this would be: https://crates.io/crates/aws-sdk-s3

**Comment by conradludgate** [comment]
I think unlikely we'd add this instead of using the server. However, it's possible to make an 
API compatible server that interfaces with S3 that you can run as a local daemon.

Notes if anyone wants to implement this themselves, It's important to consider the merging of multiple devices of history. Never just replace the uploaded data with what you have on file, always perform a merge (we don't have to worry about conflicts 👌)

**Comment by ellie** [comment]
It's a nice idea, but one we won't be implementing or supporting long term I am afraid. Multi-machine syncing would be too much of a mess - it's not just "merge these files".
