### ISSUE TITLE
RowNotFound error after deletion

### ISSUE THREAD

**Issue by ealap** [ellie/atuin#843]
I tried the new 'delete history' feature on Ubuntu and MacOS. It was all working fine until I encountered the following error on MacOS (zsh shell) when executing `atuin sync`:

```
Error: no rows returned by a query that expected to return at least one row
```

How do I recover from this?

**Comment by ellie** [comment]
Could you try “atuin sync —force”?

**Comment by ellie** [comment]
Is there much of a difference in count between the history on one machine and the other?

I believe this is happening because the client is trying to delete something it doesn't even have saved yet. A force should have resolved that though. Do you have the full error message?

**Comment by ellie** [comment]
https://github.com/ellie/atuin/pull/844

I _think_ that may resolve it, if you're able to test the branch I'd really appreciate it. Otherwise, a bit more detail on where I think this is coming from

`curl -H "Authorization: Token $(cat ~/.local/share/atuin/session) https://my.server/sync/status" will return a json object. We're interested in the `deleted`. This is a list of IDs, and on a sync download Atuin will ensure that every single one of those IDs is deleted locally.

I'm 99% sure this is happening because your client told the sync server to delete some IDs that don't exist on all the machines yet, so on the download step the client is trying to fetch a row and failing

If you haven't already, could you run `atuin sync --force` first on your Ubuntu client, and then on the mac please?

**Comment by ellie** [comment]
> #844 works and atuin is now able to sync successfully again

Great! Thanks for testing it out and sorry for the hassle!

**Comment by ellie** [comment]
It'll ignore it and allow the sync process to continue as normal. It can't delete something if it isn't there

Sync will _eventually_ ensure all items are deleted, but won't be able to do so if the process can't continue
