### ISSUE TITLE
Key creation order

### ISSUE THREAD

**Issue by ClashTheBunny** [ellie/atuin#85]
I found the key creation order to be a little confusing.  It isn't created when you register, but when you sync the first time.  So I tried to register, then login, and I couldn't find where the key was that I needed to use.

**Comment by conradludgate** [comment]
Yes it's a little confusing at the moment. I think `atuin register` and `atuin login` should maybe be a bit more explicit, where they both say whether the user has been logged in and where the key file was created

**Comment by ellie** [comment]
I can totally see how this is confusing - right now key creation is "lazy". This should probably be changed so that keys are created upon registration (if not already existing)

For now, if you need to access the key it might be best to use `atuin key`, rather than try and access the file directly, it'll ensure that the file is created if it doesn't already exist.

**Comment by ClashTheBunny** [comment]
Key just tries to read the key and then errors out:
https://github.com/ellie/atuin/blob/bd4db1fa038bc338f2b608858c2ffd3c25e0abe7/src/command/mod.rs#L145

**Comment by ellie** [comment]
I stand corrected! Sorry about that, I'll get it sorted
