### ISSUE TITLE
History a little too easy to accidentally delete

### ISSUE THREAD

**Issue by zephraph** [ellie/atuin#877]
As I unfortunately just found out `atuin search --delete` deletes all your history. My suspicion is folks wouldn't invoke that with the intention of deleting all your history. I was sort of expecting it to let me choose (kind of like #854) suggests. To prevent future people from repeating my Friday afternoon misfortune, can we at least warn folks about what will be deleted before deleting it?

**Comment by ellie** [comment]
Oh yikes, sorry about that! 😭  

> My suspicion is folks wouldn't invoke that with the intention of deleting all your history

I know of several instances where people have done that with the explicit intent of deleting all their history, but this does seem way too easy to get wrong 🙃 

The original intent was for it to work similarly to the --delete flag to `find`, but I'll see about getting a confirmation dialogue in. 

Otherwise, we will be adding deletion to the interactive UI, but will be doing it as part of a larger UI change!

**Comment by ellie** [comment]
I've just opened this to try and make it harder to accidentally delete everything!

https://github.com/ellie/atuin/pull/878

We might be able to recover your history, if you haven't already managed to somehow. Would you like me to see if it can be sorted?

**Comment by YummyOreo** [comment]
another idea, is to list out what (or how much) will be deleted and ask for confirmation

**Comment by zephraph** [comment]
> If you're using sync, we might be able to recover your history. If you haven't already managed to somehow. Would you like me to see if it can be sorted?

I'm not unfortunately, I was just running it locally. It's all good, not the end of the world. A simple option here may be just to have an empty argument to fail. I haven't tried wildcards but I could see `atuin search --delete *` deleting everything. Ultimately confirming destructive actions would probably be a better longer term UX (if for no other reason than to save me from myself lol).

**Comment by mentalisttraceur** [comment]
I think an interesting question here is whether or not this CLI is conceptually more of a UI (for humans) or an API (for programs).

Obviously this isn't mutually exclusive, since humans are the ones who end up programming use of the APIs. But I maybe if we imagine a variety of programmatic uses of this interface, we'll notice that unqualified delete hitting everything is super useful somehow.

(Like how at the human level people are sometimes tempted to return a single thing instead of a list of one element when there's only one result, but for programmatic use, the regularity of always getting a list even if it has one or zero elements ends up being more useful.)

Having said that though, I think a good case could be made that unlike regular search, delete should be an *additive* interface rather than a subtractive one: where the default is to delete *nothing*, and further parameters add things to that empty to-be-deleted set.

**Comment by ellie** [comment]
> > If you're using sync, we might be able to recover your history. If you haven't already managed to somehow. Would you like me to see if it can be sorted?
> 
> I'm not unfortunately, I was just running it locally. It's all good, not the end of the world. A simple option here may be just to have an empty argument to fail. I haven't tried wildcards but I could see `atuin search --delete *` deleting everything. Ultimately confirming destructive actions would probably be a better longer term UX (if for no other reason than to save me from myself lol).

Ahh ok, no worries. I've merged the PR I mentioned - it was more or less what you suggest there, so this should not happen again. Sorry about the not-so-great experience you had here!
