### ISSUE TITLE
Outgoing network connection when used in offline mode

### ISSUE THREAD

**Issue by sashkab** [ellie/atuin#959]
I followed instructions to install atuin in standalone mode, and expected it won't be making any network connections. 
To my surprise, an outgoing network connection was detected by Little snitch to https://api.atuin.sh the moment I invoked history by pressing ctrl+R. 

I went through config and found that there is an update check, which is probably what caused this outgoing network connection. (Please correct me if I'm wrong). 

Perhaps you should mention this in the readme to allow user to disable update check, and let the package manager deal with updates; or ask user on first run if automated update checking should be enabled.

**Comment by YummyOreo** [comment]
> I went through config and found that there is an update check, which is probably what caused this outgoing network connection. (Please correct me if I'm wrong).

Update check will make a connection but so will `auto_sync = true` if you\`re using sync (This will make a connection to the set server `sync_address` which is defaulted to `api.atuin.sh`)! `auto_sync` will every command run if the set time (`sync_frequency = "1h"`) has elapsed since the last check (afaik).

**Comment by sashkab** [comment]
>>  I followed instructions to install atuin in standalone mode

> so will `auto_sync = true` if you`re using sync

I did not login to any server, therefore I expected this wouldn't apply to me. Am I wrong?

**Comment by ellie** [comment]
It only will if you’re using sync - so in your case, it’s just the update
check

I can make the docs more prominent later, and make a compile time feature
so package managed releases don’t need it

Since making it default-on, the number of issues we’ve had due to people
running out of date versions has gone down _massively_, so I’m loathe to
change it

**Comment by sashkab** [comment]
@ellie I made #960 to mention option to disable update check in the offline installation instructions. This should be sufficient.

**Comment by conradludgate** [comment]
There is the sync feature that is default enabled. You can disable it if you're comfortable building atuin yourself.

```
cargo install atuin --no-default-features --features client
```
Would disable the server and sync features so you only get the local client only features

**Comment by sashkab** [comment]
With the merge of #960, I probably will close this.
